[PRMT-1289] Remove slim image version, add curl and lock node version

diff --git a/tasks b/tasks
--- a/tasks
+++ b/tasks
@@ -4,10 +4,11 @@ set -Eeuo pipefail
 
 DOCKER_OPS_VERSION="2.0.0"
 DOCKER_OPS_FILE="ops/docker-ops-${DOCKER_OPS_VERSION}"
+AWS_REGION="eu-west-2"
 
 mkdir -p ops
 if [[ ! -f $DOCKER_OPS_FILE ]];then
-  wget --quiet -O $DOCKER_OPS_FILE https://github.com/kudulab/docker-ops/releases/download/${DOCKER_OPS_VERSION}/docker-ops
+    wget --quiet -O $DOCKER_OPS_FILE https://github.com/kudulab/docker-ops/releases/download/${DOCKER_OPS_VERSION}/docker-ops
 fi
 source $DOCKER_OPS_FILE
 
@@ -15,38 +16,40 @@ image_name="nhsdev/node-dojo"
 image_registry="dockerhub"
 image_dir="./image"
 
-function docker_login {
-  if [ -z "$DOCKERHUB_PASSWORD" ]; then
-    echo "DOCKERHUB_PASSWORD must be your dockerhub password or an API token"
-    exit 5;
+function get_aws_ssm_secret {
+  secret_id=$1
+  json=$(dojo "aws ssm get-parameter --with-decryption --region $AWS_REGION --name $secret_id")
+  if [ $? != 0 ]; then
+    >&2 echo "Failed to obtain AWS secret from SSM: $secret_id"
+    exit 5
   fi
-  echo "$DOCKERHUB_PASSWORD" | docker login --username nhstomzo --password-stdin
+  echo $json | jq -r ".Parameter.Value"
+}
+
+function docker_login {
+    if [ -z "$DOCKERHUB_PASSWORD" ]; then
+        echo "DOCKERHUB_PASSWORD must be your dockerhub password or an API token"
+        exit 5;
+    fi
+    echo "$DOCKERHUB_PASSWORD" | docker login --username nhstomzo --password-stdin
 }
 
 command="$1"
 set +u
 case "${command}" in
-  build_local)
-      image_tag=$(git rev-parse HEAD)
-      docker_ops::docker_build "${image_dir}/alpine" "${imagerc_filename}" "${image_name}" "${image_tag}" "${image_registry}"
-      ;;
-  build_local_slim)
-      image_tag="$(git rev-parse HEAD)-slim"
-      docker_ops::docker_build "${image_dir}/slim" "${imagerc_filename}" "${image_name}" "${image_tag}" "${image_registry}"
-      ;;
-  build_slim)
-      docker_login
-      ./tasks build_local_slim
-      docker_ops::push "${image_dir}/slim" "${imagerc_filename}"
-      ;;
-  build)
-      docker_login
-      ./tasks build_local
-      docker_ops::push "${image_dir}/alpine" "${imagerc_filename}"
-      ;;
-  *)
-      echo "Invalid command: '${command}'"
-      exit 1
-      ;;
+    build_local)
+        image_tag=$(git rev-parse HEAD)
+        docker_ops::docker_build "${image_dir}" "${imagerc_filename}" "${image_name}" "${image_tag}" "${image_registry}"
+    ;;
+    build)
+        DOCKERHUB_PASSWORD=$(get_aws_ssm_secret "/repo/prod/user-input/gocd-dockerhub-password")
+        docker_login
+        ./tasks build_local
+        docker_ops::push "${image_dir}" "${imagerc_filename}"
+    ;;
+    *)
+        echo "Invalid command: '${command}'"
+        exit 1
+    ;;
 esac
 set +e
